-- ============================================================================
-- Lumen source_ratings seed — our OWN editorial estimates of credibility +
-- political lean for well-known outlets. Labeled rated_by='seed'.
-- NOT a redistribution of AllSides / MBFC / Ad Fontes data.
-- Safe to re-run: ON CONFLICT DO NOTHING (never clobbers existing rows).
-- credibility_tier: high | medium | low | unknown
-- political_lean:   left | lean-left | center | lean-right | right | unknown
-- ============================================================================

insert into public.source_ratings (domain, credibility_tier, political_lean, rated_by) values
  -- Wire services / agencies
  ('reuters.com','high','center','seed'),
  ('apnews.com','high','center','seed'),
  ('afp.com','high','center','seed'),
  ('ptinews.com','high','center','seed'),
  ('bloomberg.com','high','center','seed'),

  -- US — broadcast / national
  ('nytimes.com','high','lean-left','seed'),
  ('washingtonpost.com','high','lean-left','seed'),
  ('wsj.com','high','center','seed'),
  ('usatoday.com','high','center','seed'),
  ('npr.org','high','lean-left','seed'),
  ('pbs.org','high','center','seed'),
  ('abcnews.go.com','high','lean-left','seed'),
  ('cbsnews.com','high','lean-left','seed'),
  ('nbcnews.com','high','lean-left','seed'),
  ('cnn.com','medium','lean-left','seed'),
  ('msnbc.com','medium','left','seed'),
  ('foxnews.com','medium','right','seed'),
  ('politico.com','high','lean-left','seed'),
  ('axios.com','high','center','seed'),
  ('thehill.com','high','center','seed'),
  ('semafor.com','high','center','seed'),
  ('usnews.com','high','center','seed'),
  ('latimes.com','high','lean-left','seed'),
  ('chicagotribune.com','high','center','seed'),
  ('bostonglobe.com','high','lean-left','seed'),
  ('propublica.org','high','lean-left','seed'),
  ('factcheck.org','high','center','seed'),
  ('politifact.com','high','lean-left','seed'),
  ('snopes.com','medium','lean-left','seed'),

  -- US — magazines / opinion / digital
  ('theatlantic.com','high','lean-left','seed'),
  ('newyorker.com','high','left','seed'),
  ('vox.com','medium','left','seed'),
  ('slate.com','medium','left','seed'),
  ('motherjones.com','medium','left','seed'),
  ('huffpost.com','medium','left','seed'),
  ('theintercept.com','medium','left','seed'),
  ('buzzfeednews.com','medium','lean-left','seed'),
  ('time.com','medium','lean-left','seed'),
  ('newsweek.com','medium','center','seed'),
  ('nationalreview.com','medium','right','seed'),
  ('reason.com','medium','lean-right','seed'),
  ('thedispatch.com','high','lean-right','seed'),
  ('washingtonexaminer.com','medium','right','seed'),
  ('nypost.com','medium','lean-right','seed'),
  ('thefreepress.com','medium','lean-right','seed'),
  ('dailywire.com','medium','right','seed'),
  ('breitbart.com','low','right','seed'),
  ('theblaze.com','low','right','seed'),
  ('newsmax.com','low','right','seed'),
  ('oann.com','low','right','seed'),
  ('theepochtimes.com','low','right','seed'),
  ('dailykos.com','low','left','seed'),
  ('alternet.org','low','left','seed'),
  ('infowars.com','low','right','seed'),

  -- US — business / finance
  ('cnbc.com','high','center','seed'),
  ('marketwatch.com','high','center','seed'),
  ('barrons.com','high','center','seed'),
  ('forbes.com','medium','center','seed'),
  ('fortune.com','medium','center','seed'),
  ('businessinsider.com','medium','lean-left','seed'),
  ('qz.com','medium','lean-left','seed'),

  -- UK
  ('bbc.com','high','center','seed'),
  ('bbc.co.uk','high','center','seed'),
  ('theguardian.com','high','lean-left','seed'),
  ('telegraph.co.uk','high','lean-right','seed'),
  ('thetimes.co.uk','high','center','seed'),
  ('ft.com','high','center','seed'),
  ('independent.co.uk','high','lean-left','seed'),
  ('economist.com','high','center','seed'),
  ('news.sky.com','high','center','seed'),
  ('metro.co.uk','medium','center','seed'),
  ('mirror.co.uk','medium','lean-left','seed'),
  ('spectator.co.uk','medium','right','seed'),
  ('dailymail.co.uk','low','right','seed'),
  ('thesun.co.uk','low','lean-right','seed'),

  -- International
  ('aljazeera.com','high','lean-left','seed'),
  ('dw.com','high','center','seed'),
  ('france24.com','high','center','seed'),
  ('euronews.com','high','center','seed'),
  ('politico.eu','high','center','seed'),
  ('cbc.ca','high','lean-left','seed'),
  ('theglobeandmail.com','high','center','seed'),
  ('nationalpost.com','high','lean-right','seed'),
  ('abc.net.au','high','center','seed'),
  ('smh.com.au','high','lean-left','seed'),
  ('scmp.com','high','center','seed'),
  ('japantimes.co.jp','high','center','seed'),
  ('straitstimes.com','high','center','seed'),
  ('haaretz.com','high','lean-left','seed'),
  ('timesofisrael.com','high','center','seed'),
  ('jpost.com','high','lean-right','seed'),
  ('rt.com','low','right','seed'),
  ('sputnikglobe.com','low','unknown','seed'),

  -- India
  ('thehindu.com','high','lean-left','seed'),
  ('indianexpress.com','high','center','seed'),
  ('livemint.com','high','center','seed'),
  ('business-standard.com','high','center','seed'),
  ('economictimes.indiatimes.com','high','center','seed'),
  ('thehindubusinessline.com','high','center','seed'),
  ('moneycontrol.com','high','center','seed'),
  ('deccanherald.com','high','center','seed'),
  ('rbi.org.in','high','center','seed'),
  ('ndtv.com','medium','lean-left','seed'),
  ('hindustantimes.com','medium','center','seed'),
  ('timesofindia.indiatimes.com','medium','center','seed'),
  ('indiatoday.in','medium','center','seed'),
  ('news18.com','medium','lean-right','seed'),
  ('firstpost.com','medium','lean-right','seed'),
  ('theprint.in','medium','center','seed'),
  ('scroll.in','medium','lean-left','seed'),
  ('thewire.in','medium','left','seed'),
  ('thequint.com','medium','lean-left','seed'),
  ('newslaundry.com','medium','lean-left','seed'),
  ('telegraphindia.com','medium','lean-left','seed'),
  ('swarajyamag.com','medium','right','seed'),
  ('opindia.com','low','right','seed'),
  ('republicworld.com','low','right','seed'),

  -- Science / health / official
  ('nature.com','high','center','seed'),
  ('science.org','high','center','seed'),
  ('nejm.org','high','center','seed'),
  ('thelancet.com','high','center','seed'),
  ('who.int','high','center','seed'),
  ('nih.gov','high','center','seed'),
  ('cdc.gov','high','center','seed'),
  ('nasa.gov','high','center','seed'),
  ('imf.org','high','center','seed'),
  ('worldbank.org','high','center','seed'),
  ('arxiv.org','high','center','seed'),
  ('pubmed.ncbi.nlm.nih.gov','high','center','seed'),
  ('nationalgeographic.com','high','center','seed'),
  ('scientificamerican.com','high','lean-left','seed'),
  ('newscientist.com','high','center','seed'),

  -- Tech
  ('techcrunch.com','medium','center','seed'),
  ('theverge.com','medium','lean-left','seed'),
  ('wired.com','medium','lean-left','seed'),
  ('arstechnica.com','high','center','seed'),
  ('engadget.com','medium','center','seed'),
  ('cnet.com','medium','center','seed'),
  ('zdnet.com','medium','center','seed'),
  ('venturebeat.com','medium','center','seed'),
  ('theregister.com','medium','center','seed'),
  ('404media.co','medium','lean-left','seed'),
  ('restofworld.org','high','center','seed'),

  -- Publishing platforms (author-dependent, so treated as medium)
  ('medium.com','medium','center','seed'),
  ('substack.com','medium','center','seed'),

  -- Reference / encyclopedic
  ('wikipedia.org','medium','center','seed'),
  ('britannica.com','high','center','seed')
on conflict (domain) do nothing;
