import { z } from "zod";
import {
  isSupabaseConfigured,
  isEmbeddingsConfigured,
  isExtendedCompute,
} from "@/lib/env";
import { createClient } from "@/lib/supabase/server";
import { checkRateLimit, cacheGet, cacheSet } from "@/lib/cache/redis";
import {
  normalizeQuery,
  detectInputType,
  gatherSearchSources,
  gatherUrlSource,
  type PreparedSource,
} from "@/lib/search/pipeline";
import { buildMessages } from "@/lib/ai/prompts";
import { streamSummary } from "@/lib/ai/summarize";
import { generateAnalysis } from "@/lib/ai/analysis";
import { parseArticle } from "@/lib/ai/parse";
import { resolveModelId, modelSlug, isThinkingModel } from "@/lib/ai/model-catalog";
import { resolveFormat } from "@/lib/ai/formats";
import { planResearch, gatherDeepSources } from "@/lib/ai/research";
import { getUserTier, TIER_LABEL, searchDepth } from "@/lib/billing/entitlements";
import { categorizeSearch } from "@/lib/library/categorize";
import { indexSummary } from "@/lib/library/embeddings-index";
import { createSearch, markSearchError, persistResult } from "@/lib/search/persist";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";
// Max searches (Opus + deep sourcing + analysis) can run long. 300s needs a
// Vercel plan that allows it (Pro); Hobby clamps this to its 60s ceiling.
export const maxDuration = 300;

const bodySchema = z.object({
  query: z.string().trim().min(2).max(500),
  // "deep" arrives in a later phase; accept it but treat as quick for now.
  mode: z.enum(["quick", "deep"]).optional().default("quick"),
  // User-chosen article model id; clamped server-side to the tier's allowlist.
  model: z.string().max(40).optional(),
  // Output lens (see formats.ts); unknown values fall back to "standard".
  format: z.string().max(20).optional(),
});

// Source fields we cache (no extracted body) and send to the client.
type SourceMeta = Omit<PreparedSource, "content">;

interface CachedResult {
  title: string;
  markdown: string;
  sources: SourceMeta[];
  aiAnalysis?: string | null;
}

const CACHE_TTL_SECONDS = 60 * 60 * 24; // 24h for the "week" freshness window

function jsonError(message: string, status: number) {
  return Response.json({ error: message }, { status });
}

export async function POST(req: Request) {
  const parsed = bodySchema.safeParse(await req.json().catch(() => null));
  if (!parsed.success) return jsonError("Enter a topic or link to search.", 400);
  const { query } = parsed.data;

  if (!isSupabaseConfigured()) {
    return jsonError("The app isn't fully configured yet. Add API keys to .env.local.", 503);
  }

  const supabase = await createClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();
  if (!user) return jsonError("Please sign in to search.", 401);

  // Server-authoritative tier — drives which models the user may use.
  const tier = await getUserTier(supabase, user.id);
  // Clamp the (optional) client model choice to this tier's allowlist.
  const modelId = resolveModelId(tier, parsed.data.model);
  const model = modelSlug(modelId);
  // Cap reasoning for thinking models so they stay within the request timeout.
  const reasoningEffort = isThinkingModel(modelId) ? ("low" as const) : undefined;
  // Deep research (Max + extended compute): plan → multi-search → synthesize a
  // longer structured report. Falls back to a normal search when ineligible.
  const deep =
    parsed.data.mode === "deep" && tier === "max" && isExtendedCompute();
  const mode = deep ? ("deep" as const) : ("quick" as const);
  // Deep runs force the in-depth lens; otherwise use the requested output lens.
  const format = resolveFormat(deep ? "deep" : parsed.data.format);

  const rl = await checkRateLimit(supabase, user.id, tier);
  if (!rl.allowed) {
    const msg =
      tier === "max"
        ? `You've hit your hourly limit of ${rl.limit} searches. Try again shortly.`
        : `You've hit your ${TIER_LABEL[tier]} limit of ${rl.limit} searches/hour. Upgrade for a higher cap, or try again shortly.`;
    return jsonError(msg, 429);
  }

  const inputType = detectInputType(query);
  const normalizedQuery = normalizeQuery(query);
  // Segment the cache by the resolved model, so a result generated by one model
  // is never served for a request that asked for a different one. (Model id
  // also encodes the tier boundary — free-only Haiku vs the paid models.)
  const cacheKey = `sum:${mode}:${modelId}:${format.id}:${
    inputType === "url" ? query.trim().toLowerCase() : normalizedQuery
  }`;

  const encoder = new TextEncoder();
  const stream = new ReadableStream<Uint8Array>({
    async start(controller) {
      const send = (obj: unknown) =>
        controller.enqueue(encoder.encode(JSON.stringify(obj) + "\n"));

      // Auto-categorize after `done` so it never delays the result. Best-effort.
      const categorize = async (sid: string, title: string) => {
        try {
          await categorizeSearch(supabase, {
            userId: user.id,
            searchId: sid,
            title,
            query,
          });
        } catch (err) {
          console.error("categorize failed:", err);
        }
      };

      // Extended compute (Vercel Pro): index the fresh article into the semantic
      // library right here, so "Ask your library" / "Related" include it
      // immediately — no separate backfill round-trip. Runs after `done`, so it
      // never affects perceived latency. Best-effort; Pro/Max only.
      const indexInline = async (sid: string) => {
        if (tier === "free" || !isExtendedCompute() || !isEmbeddingsConfigured())
          return;
        try {
          await indexSummary(supabase, user.id, sid);
        } catch (err) {
          console.error("inline library index failed:", err);
        }
      };

      let searchId: string | undefined;
      try {
        searchId = await createSearch(supabase, {
          userId: user.id,
          query,
          normalizedQuery,
          inputType,
          mode,
        });

        /* ---------- cache hit: re-use generation, persist for user ---------- */
        const cached = await cacheGet<CachedResult>(cacheKey);
        // Ignore a legacy empty cache entry and regenerate instead of replaying
        // a blank article.
        if (cached && cached.markdown.trim()) {
          send({ type: "status", phase: "cached", message: "Found a recent result" });
          send({ type: "sources", sources: cached.sources });

          // Stream the cached markdown in small chunks for a live feel.
          for (const chunk of chunkString(cached.markdown, 240)) {
            send({ type: "delta", text: chunk });
          }

          // Cache is segmented by tier, so cached.aiAnalysis only exists for
          // paid tiers; replay it.
          const cachedAnalysis = tier !== "free" ? cached.aiAnalysis ?? null : null;
          if (cachedAnalysis) send({ type: "analysis", text: cachedAnalysis });

          const article = parseArticle(cached.markdown, query);
          const summaryId = await persistResult(supabase, {
            userId: user.id,
            searchId,
            article,
            sources: cached.sources.map((s) => ({ ...s, content: "" })),
            modelUsed: model,
            aiAnalysis: cachedAnalysis,
          });
          send({
            type: "done",
            summaryId,
            title: article.title,
            lengthKind: article.lengthKind,
            citationCoverage: article.citationCoverage,
            tier,
          });
          await categorize(searchId, article.title);
          await indexInline(summaryId);
          return;
        }

        /* ------------------------- gather sources ------------------------- */
        send({ type: "status", phase: "searching", message: "Searching credible sources" });

        let sources: PreparedSource[];
        if (inputType === "url") {
          sources = await gatherUrlSource(query);
        } else if (deep) {
          send({ type: "status", phase: "searching", message: "Planning the research" });
          const subs = await planResearch(query);
          send({
            type: "status",
            phase: "reading",
            message: subs.length
              ? `Researching ${subs.length + 1} angles`
              : "Gathering sources",
          });
          sources = await gatherDeepSources(query, subs);
        } else {
          const { sources: sourceCount, contentBudget } = searchDepth(tier);
          sources = await gatherSearchSources(query, {
            count: sourceCount,
            contentBudget,
          });
        }

        if (sources.length === 0) {
          send({
            type: "error",
            message:
              "Couldn't find usable sources for that. Try rephrasing or a different topic.",
          });
          await markSearchError(supabase, searchId, "no sources found");
          return;
        }

        const sourceMeta: SourceMeta[] = sources.map(toMeta);
        send({ type: "sources", sources: sourceMeta });

        /* --------------------------- summarize ---------------------------- */
        send({ type: "status", phase: "writing", message: "Writing your article" });

        const messages = buildMessages({ query, inputType, sources, format: format.id });
        let markdown = "";
        for await (const delta of streamSummary({
          model,
          messages,
          reasoningEffort,
          maxTokens: format.maxTokens,
        })) {
          markdown += delta;
          send({ type: "delta", text: delta });
        }

        const article = parseArticle(markdown, query);

        // Guard against an empty/failed generation: don't persist or cache a
        // blank article (it would otherwise be replayed for 24h). Surface an
        // error so the user can retry.
        if (!article.blocks.some((b) => b.type === "text")) {
          send({
            type: "error",
            message:
              "The article came back empty. Please try again in a moment.",
          });
          await markSearchError(supabase, searchId, "empty article");
          return;
        }

        /* -------- Persist the article NOW, before the slow analysis -------- */
        // Saving here (not after AI Analysis) guarantees the article lands in
        // the library and the reader/chat work — even if the analysis pass is
        // slow or the serverless function is cut short by its time limit.
        const summaryId = await persistResult(supabase, {
          userId: user.id,
          searchId,
          article,
          sources,
          modelUsed: model,
          aiAnalysis: null,
        });

        await cacheSet<CachedResult>(
          cacheKey,
          { title: article.title, markdown, sources: sourceMeta, aiAnalysis: null },
          CACHE_TTL_SECONDS,
        );

        send({
          type: "done",
          summaryId,
          title: article.title,
          lengthKind: article.lengthKind,
          citationCoverage: article.citationCoverage,
          tier,
        });
        await categorize(searchId, article.title);

        /* ------ AI Analysis (Pro/Max): best-effort, streams after done ----- */
        if (tier !== "free") {
          try {
            const text = await generateAnalysis({
              model,
              query,
              articleMarkdown: markdown,
              sources: sourceMeta,
              reasoningEffort,
            });
            if (text) {
              send({ type: "analysis", text });
              await supabase
                .from("summaries")
                .update({ ai_analysis: text })
                .eq("id", summaryId);
              await cacheSet<CachedResult>(
                cacheKey,
                { title: article.title, markdown, sources: sourceMeta, aiAnalysis: text },
                CACHE_TTL_SECONDS,
              );
            }
          } catch (err) {
            // Never fail the (already-saved) search because analysis failed.
            console.error("analysis pass failed:", err);
          }
        }

        // Extended compute (Vercel Pro): index the article now so it's instantly
        // available to "Ask your library" / "Related". No-op otherwise.
        await indexInline(summaryId);
      } catch (err) {
        // Log the real error server-side; never leak internals to the client.
        console.error("search route error:", err);
        send({
          type: "error",
          message:
            "Something went wrong generating your article. Please try again.",
        });
        if (searchId) {
          await markSearchError(
            supabase,
            searchId,
            err instanceof Error ? err.message : "unknown error",
          );
        }
      } finally {
        controller.close();
      }
    },
  });

  return new Response(stream, {
    headers: {
      "Content-Type": "application/x-ndjson; charset=utf-8",
      "Cache-Control": "no-store",
    },
  });
}

function toMeta(s: PreparedSource): SourceMeta {
  return {
    position: s.position,
    title: s.title,
    url: s.url,
    domain: s.domain,
    publishedAt: s.publishedAt,
    credibilityTier: s.credibilityTier,
    politicalLean: s.politicalLean,
    snippet: s.snippet,
  };
}

function* chunkString(str: string, size: number): Generator<string> {
  for (let i = 0; i < str.length; i += size) yield str.slice(i, i + size);
}
