import type { SourceMeta } from "@/components/search/source-list";

export interface ExportableArticle {
  title: string;
  /** Original topic/URL query, shown as metadata. */
  query?: string;
  /** Display date string (already formatted), shown as metadata. */
  date?: string;
  bodyMarkdown: string;
  sources: SourceMeta[];
}

const TIER_LABEL: Record<SourceMeta["credibilityTier"], string> = {
  high: "High credibility",
  medium: "Medium credibility",
  low: "Unverified",
  unknown: "Unknown",
};

/** Escape Markdown link-text delimiters so a source title can't break the link. */
function escapeLinkText(s: string): string {
  return s.replace(/([[\]])/g, "\\$1");
}

/**
 * Assemble a portable Markdown document from a saved article: title, optional
 * metadata, the cited body (with its inline [n] markers preserved), and a
 * numbered Sources list that those markers map to.
 */
export function buildExportMarkdown(a: ExportableArticle): string {
  const parts: string[] = [`# ${a.title.trim()}`];

  const meta: string[] = [];
  if (a.query) meta.push(`**Topic:** ${a.query}`);
  if (a.date) meta.push(`**Saved:** ${a.date}`);
  if (meta.length) parts.push(meta.join("  \n"));

  const body = a.bodyMarkdown.trim();
  if (body) parts.push(body);

  if (a.sources.length > 0) {
    const list = a.sources
      .map((s) => {
        const label = escapeLinkText(s.title || s.domain || s.url);
        const bits = [s.domain, TIER_LABEL[s.credibilityTier]].filter(Boolean);
        const suffix = bits.length ? ` — ${bits.join(" · ")}` : "";
        return `${s.position}. [${label}](${s.url})${suffix}`;
      })
      .join("\n");
    parts.push(`## Sources\n\n${list}`);
  }

  parts.push(`---\n\n_Generated by [Lumen](https://lumenlm.vercel.app)_`);
  return `${parts.join("\n\n")}\n`;
}

/** Filesystem-safe `.md` filename from an article title. */
export function exportFilename(title: string): string {
  const slug = title
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 60);
  return `${slug || "article"}.md`;
}
